services:
  # nginx:
  #   image: nginx:1.21
  #   # restart: always
  #   depends_on:
  #     - node-proxy
  #   ports:
  #     - 0.0.0.0:80:80
  #   volumes:
  #     - ./configs/nginx/conf.d/:/etc/nginx/conf.d/

  node-proxy:
    build: ./app
    restart: always
    environment: 
      NODE_ENV: production
      TARGET_URL: http://localhost:8081/
    ports: 
      - 8080:3000

    volumes: 
      - ./app/build/:/usr/src/app/build/
      - ./app/assets/:/usr/src/app/assets/
